### ISSUE TITLE
Tests Failing on OS X: Unable to download nodewebkit

### ISSUE THREAD

**Issue by btjones** [edjafarov/node-webkit-updater#77] opened 2015-03-02 18:55 UTC
```
Fatal error: Unable to download nodewebkit.
```

![screen shot 2015-03-02 at 1 47 38 pm](https://cloud.githubusercontent.com/assets/155808/6447798/73c52580-c0e3-11e4-86c3-18affd9abd3a.png)

Not sure if I'm doing something wrong or if this is a real issue. I ran `npm run deps` before running `npm test`. I'm on OS X 10.9.5.

**Comment by ecstaticpeon** [comment] 2015-03-09 17:13
I'm getting the same issue on Linux 64 (Ubuntu 14.04).

```
git clone https://github.com/edjafarov/node-webkit-updater.git
cd node-webkit-updater/
npm install
npm test
```

**Comment by y-lohse** [comment] 2015-03-10 10:14
Same on windows 7 64.

My initial hunch is that it's related to dl.node-webkit.org being redirected to dl.nwjs.io. This is handled by the [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder) module. Version 0.2.2 is used here, most recent is 1.2.0.

if your platform is in [here](http://dl.nwjs.io/v0.9.2/) there's a good chance that just upgrading to the latest node-webkit-builder will solve the issue.

**Comment by y-lohse** [comment] 2015-03-10 15:39
I confirm, updating to a newer version of grunt-node-webkit-builder solves this, see [this commit](https://github.com/CalderaGraphics/node-webkit-updater/commit/480e10574c56625bed0ee63ddbc18261ee3a21c7).

That said, on mac & windows it's still not perfect because the latest versions of nwjs include 32 & 64 bit versions for those platforms, whereas the current node-webkit-updater test code isn't meant for that. Are there any plans regarding this? @adam-lynch ?

**Comment by adam-lynch** [comment] 2015-03-10 16:38
As far as I know, there isn't much that would need to change (if anything) to support 32 and 64-bit. Right?

**Comment by y-lohse** [comment] 2015-03-10 16:57
I don't think so, no. I could probably patch & PR it if that's something you guys want to have part of the updater. It would definitely make sense.

**Comment by y-lohse** [comment] 2015-03-11 11:52
Turns out it's not that trivial, the updater code is affected as well. [Here's my work so far](https://github.com/CalderaGraphics/node-webkit-updater/commit/83077c7d44c49856da42dc8a356123fc41902485), it seems to work fairly well.

The tests run up to the [opened and updated](https://github.com/CalderaGraphics/node-webkit-updater/blob/master/test/basicTest.spec.js#L170) log, but the test don't end and the app doesn't close itself.
Inspecting the app itself, it displays a `copying app` message and the console chokes on the following error: `Uncaught TypeError: Incorrect value of args option` in a child process. Indeed, the [logged args](https://github.com/CalderaGraphics/node-webkit-updater/blob/master/test/basicTest.spec.js#L168) are empty.

I'd really appreciate some insight from someones who's more familiar with the code base & maybe ran the tests before:

- what is the expected behavior? 
- The test is waiting for [something from express](https://github.com/CalderaGraphics/node-webkit-updater/blob/master/test/basicTest.spec.js#L164) to complete itself but I fail to understand what exactly.
- At that point, why is the app still trying to [install something](https://github.com/CalderaGraphics/node-webkit-updater/blob/master/app/index.html#L50)? AFAIK it's already updated & installed. Is that code broken?

Thanks :-)

**Comment by y-lohse** [comment] 2015-03-23 13:06
@edjafarov or @adam-lynch ? Any ideas?

**Comment by gladwinput** [comment] 2015-08-10 12:16
@y-lohse - I grabbed your work so far. Works a peach on windows versions. Of course you get that "copying app" issue but as long as you hide it, the user for now won't notice, as app is correct. Then the next time they load the app it is updated anyway.

However I notice the mac version fails still unfortunately, object undefined on line 157 of updater.js

**Comment by gladwintech** [comment] 2015-09-05 12:29
Any update on this one?

**Comment by Karlheinzniebuhr** [comment] 2015-09-07 03:42
same issue here

**Closed** 2022-05-24 17:58 UTC
